# Generated by Django 3.2 on 2023-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='abd', max_length=256),
            preserve_default=False,
        ),
    ]
